server:
  port: 8080
  spring:
    datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver
    path: /h2-console
    enabled: true